import React, { useState } from "react";
import { Check, ExternalLink, Copy, CheckCheck, Sparkles, HelpCircle } from "lucide-react";
import { ActionPlanStep, MatchedOpportunity } from "../types";

interface ActionPlanSectionProps {
  steps: ActionPlanStep[];
  top3Actions?: ActionPlanStep[];
  checked: boolean[];
  onToggle: (index: number) => void;
  onOpenOpportunity?: (oppId: string) => void;
}

export const ActionPlanSection: React.FC<ActionPlanSectionProps> = ({
  steps,
  top3Actions = [],
  checked,
  onToggle,
  onOpenOpportunity,
}) => {
  const [copied, setCopied] = useState(false);

  const completedCount = checked.filter(Boolean).length;
  const progressPct = steps.length > 0 ? Math.round((completedCount / steps.length) * 100) : 0;

  const handleCopy = () => {
    const text = steps
      .map(
        (s, i) =>
          `${i + 1}. [${checked[i] ? "COMPLETED" : "PENDING"}] (${s.priorityLevel || "HIGH"} Priority) ${s.step}\n   ${s.detail}${
            s.officialUrl ? `\n   Official Source: ${s.officialUrl}` : ""
          }`
      )
      .join("\n\n");

    navigator.clipboard.writeText(
      `ArthaAI Action Plan for MSME Growth\n==================================\n\n${text}\n\nGenerated by ArthaAI — AI Business Officer for Indian MSMEs`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const top3 = top3Actions.length > 0 ? top3Actions : steps.slice(0, 3);

  return (
    <div className="space-y-5">
      {/* START HERE — TOP THINGS WORTH ATTENTION */}
      <section className="rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50/90 via-indigo-50/40 to-white p-4 shadow-2xs dark:border-blue-900/60 dark:from-blue-950/40 dark:via-slate-900 dark:to-slate-900 sm:p-5">
        <div className="flex items-center justify-between">
          <div>
            <span className="text-[11px] font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300">
              START HERE
            </span>
            <h2 className="mt-0.5 text-base font-bold text-slate-900 dark:text-white sm:text-lg">
              Things worth your attention
            </h2>
          </div>
          <span className="rounded-full bg-blue-100 px-2.5 py-0.5 text-[11px] font-bold text-blue-800 dark:bg-blue-950 dark:text-blue-300">
            Top Matches
          </span>
        </div>

        <div className="mt-3.5 grid grid-cols-1 gap-3 md:grid-cols-3">
          {top3.map((item, idx) => {
            const isHigh = item.priorityLevel === "HIGH";
            return (
              <div
                key={idx}
                className="flex flex-col justify-between rounded-xl border border-slate-200 bg-white p-3.5 shadow-2xs dark:border-slate-800 dark:bg-slate-900"
              >
                <div>
                  <div className="flex items-center justify-between gap-2">
                    <span className="flex h-5 w-5 items-center justify-center rounded-full bg-blue-600 text-[11px] font-bold text-white">
                      {idx + 1}
                    </span>
                    <span
                      className={`rounded px-1.5 py-0.2 text-[10px] font-bold uppercase tracking-wider ${
                        isHigh
                          ? "bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300"
                          : "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300"
                      }`}
                    >
                      {item.priorityLevel || "HIGH"} PRIORITY
                    </span>
                  </div>

                  <h3 className="mt-2 text-xs font-bold text-slate-900 dark:text-white sm:text-sm">
                    {item.step}
                  </h3>
                  <p className="mt-1 text-[11px] leading-relaxed text-slate-500 dark:text-slate-400">
                    {item.detail}
                  </p>
                </div>

                <div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-2.5 dark:border-slate-800">
                  {item.opportunityId && onOpenOpportunity ? (
                    <button
                      type="button"
                      onClick={() => onOpenOpportunity(item.opportunityId!)}
                      className="inline-flex min-h-[30px] items-center gap-1 text-[11px] font-semibold text-slate-600 hover:text-blue-600 dark:text-slate-400 dark:hover:text-blue-400"
                    >
                      <HelpCircle className="h-3 w-3" />
                      <span>Why this matches</span>
                    </button>
                  ) : (
                    <span className="text-[11px] text-slate-400">Statutory directive</span>
                  )}

                  {item.officialUrl && (
                    <a
                      href={item.officialUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex min-h-[30px] items-center gap-1 rounded-lg bg-blue-50 px-2 py-1 text-[11px] font-bold text-blue-600 hover:bg-blue-100 dark:bg-blue-950/60 dark:text-blue-400 dark:hover:bg-blue-900"
                    >
                      <span>Official Source</span>
                      <ExternalLink className="h-3 w-3" />
                    </a>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* YOUR ACTION PLAN / IMPLEMENTATION CHECKLIST */}
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-2xs dark:border-slate-800 dark:bg-slate-900 sm:p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
              YOUR ACTION PLAN
            </span>
            <h2 className="text-sm font-bold text-slate-900 dark:text-white sm:text-base">
              Implementation Checklist
            </h2>
          </div>

          <button
            onClick={handleCopy}
            className="flex min-h-[36px] items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1 text-xs font-semibold text-slate-700 shadow-2xs hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-800 dark:text-slate-200"
          >
            {copied ? (
              <>
                <CheckCheck className="h-3.5 w-3.5 text-emerald-600" />
                <span className="text-emerald-600">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5 text-slate-400" />
                <span>Copy Plan</span>
              </>
            )}
          </button>
        </div>

        {/* Progress Bar */}
        <div className="mt-3.5">
          <div className="mb-1.5 flex items-center justify-between text-xs font-semibold">
            <span className="text-slate-600 dark:text-slate-300">
              {completedCount} of {steps.length} completed
            </span>
            <span className="text-blue-600 dark:text-blue-400">{progressPct}%</span>
          </div>
          <div className="h-1.5 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
            <div
              className="h-full rounded-full bg-blue-600 transition-all duration-300 dark:bg-blue-500"
              style={{ width: `${progressPct}%` }}
            />
          </div>
        </div>

        {/* Action Items List */}
        <ol className="mt-3.5 space-y-2">
          {steps.map((item, i) => {
            const isDone = checked[i] || false;
            return (
              <li
                key={i}
                className={`flex items-start gap-3 rounded-xl border p-3 transition-all ${
                  isDone
                    ? "border-slate-200/60 bg-slate-50/60 opacity-80 dark:border-slate-800 dark:bg-slate-800/40"
                    : "border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"
                }`}
              >
                <button
                  type="button"
                  onClick={() => onToggle(i)}
                  aria-label={isDone ? "Mark step as pending" : "Mark step as completed"}
                  className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition ${
                    isDone
                      ? "border-emerald-600 bg-emerald-600 text-white"
                      : "border-slate-300 hover:border-blue-600 dark:border-slate-600 dark:hover:border-blue-400"
                  }`}
                >
                  {isDone && <Check className="h-3 w-3" strokeWidth={3} />}
                </button>

                <div className="flex-1">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <span
                      className={`text-xs font-semibold ${
                        isDone
                          ? "text-slate-400 line-through dark:text-slate-500"
                          : "text-slate-900 dark:text-white"
                      }`}
                    >
                      {item.step}
                    </span>

                    {item.officialUrl && (
                      <a
                        href={item.officialUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-[11px] font-semibold text-blue-600 hover:underline dark:text-blue-400"
                      >
                        <span>Official link</span>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    )}
                  </div>

                  <p className="mt-0.5 text-[11px] leading-relaxed text-slate-500 dark:text-slate-400">
                    {item.detail}
                  </p>
                </div>
              </li>
            );
          })}
        </ol>
      </section>
    </div>
  );
};
